# Compiler shell
#python -m nuitka --standalone --plugin-enable=pyside6 --include-qt-qt-plugins=sensible,qml "C:/Users/gabri/Desktop/WEG/PYTHON PROJECTS/includIO/main.py" --include-data-file="C:/Users/gabri/Desktop/WEG/PYTHON PROJECTS/includIO/content/python/*.py"=./content/python/ --include-data-file="C:/Users/gabri/Desktop/WEG/PYTHON PROJECTS/includIO/inputio_rc.py"=./ --output-dir=C:\Users\gabri\Desktop\WEG\PYTHON PROJECTS\includIO\output
#C:\Users\gabri\Desktop\WEG\PYTHON PROJECTS\includIO\output\main.dist
### Clear Output Files that are unecessary
import os
import shutil
listToDelete = ['./output/main.dist/PySide6/translations/qtdeclarative_hr.qm', 
'./output/main.dist/PySide6/Qt6QuickTest.dll', 
'./output/main.dist/PySide6/qt-plugins/platforms/qdirect2d.dll', 
'./output/main.dist/PySide6/Qt63DQuickInput.dll', 
'./output/main.dist/PySide6/opengl32sw.dll', 
'./output/main.dist/PySide6/Qt63DLogic.dll',
'./output/main.dist/PySide6/qt-plugins/qmltooling/qmldbg_messages.dll', 
'./output/main.dist/PySide6/qml/Qt3D', 
'./output/main.dist/PySide6/Qt63DQuickRender.dll', 
'./output/main.dist/shiboken6/MSVCP140.dll', 
'./output/main.dist/PySide6/translations/qtdeclarative_sk.qm', 
'./output/main.dist/PySide6/Qt6WebChannel.dll', 
'./output/main.dist/PySide6/translations/qtdeclarative_de.qm', 
'./output/main.dist/PySide6/Qt6OpenGLWidgets.dll',
'./output/main.dist/PySide6/Qt6Widgets.dll',
'./output/main.dist/PySide6/qt-plugins/qmltooling', 
'./output/main.dist/PySide6/translations/qtbase_cs.qm', 
'./output/main.dist/PySide6/qml/QtPositioning', 
'./output/main.dist/PySide6/qml/QtRemoteObjects', 
'./output/main.dist/PySide6/Qt6ScxmlQml.dll', 
'./output/main.dist/PySide6/translations/qtdeclarative_pl.qm', 
'./output/main.dist/unicodedata.pyd', 
'./output/main.dist/PySide6/Qt6VirtualKeyboard.dll',
'./output/main.dist/PySide6/Qt6Quick3DParticleEffects.dll', 
'./output/main.dist/PySide6/translations/qtdeclarative_fa.qm',
'./output/main.dist/PySide6/qt-plugins/qmltooling/qmldbg_native.dll',
'./output/main.dist/PySide6/Qt6QuickShapes.dll', 
'./output/main.dist/PySide6/Qt6WebEngineQuick.dll',
'./output/main.dist/PySide6/translations/qtbase_hu.qm',
'./output/main.dist/PySide6/translations/qtbase_ar.qm', 
'./output/main.dist/PySide6/translations/qtdeclarative_uk.qm', 
'./output/main.dist/PySide6/qml/QtWebSockets', 
'./output/main.dist/PySide6/translations/qtdeclarative_lv.qm', 
'./output/main.dist/PySide6/qml/QtQml/qt-plugins.qmltypes',
'./output/main.dist/PySide6/Qt63DAnimation.dll', 
'./output/main.dist/PySide6/translations/qtbase_nn.qm', 
'./output/main.dist/PySide6/translations/qtbase_lv.qm', 
'./output/main.dist/PySide6/translations/qtbase_de.qm',
'./output/main.dist/PySide6/Qt6Sensors.dll', 
'./output/main.dist/PySide6/translations/qtdeclarative_ru.qm', 
'./output/main.dist/PySide6/translations/qtbase_ja.qm',
'./output/main.dist/PySide6/translations/qtdeclarative_bg.qm', 
'./output/main.dist/PySide6/qt-plugins/qmltooling/qmldbg_quick3dprofiler.dll',
'./output/main.dist/PySide6/Qt6MultimediaQuick.dll', 
'./output/main.dist/PySide6/qml/QtQml/XmlListModel', 
'./output/main.dist/PySide6/qml/QtQuick3D', 
'./output/main.dist/PySide6/Qt6Scxml.dll', 
'./output/main.dist/PySide6/translations/qtbase_da.qm', 
'./output/main.dist/PySide6/translations/qtdeclarative_ja.qm', 
'./output/main.dist/PySide6/translations/qtdeclarative_hu.qm', 
'./output/main.dist/PySide6/translations/qtbase_it.qm', 
'./output/main.dist/PySide6/Qt6LabsQmlModels.dll',
'./output/main.dist/PySide6/translations/qtdeclarative_da.qm', 
'./output/main.dist/PySide6/qml/QtMultimedia', 
'./output/main.dist/PySide6/Qt6RemoteObjects.dll',
'./output/main.dist/PySide6/translations/qtbase_fr.qm', 
'./output/main.dist/PySide6/qml/QtDataVisualization', './output/main.dist/PySide6/Qt63DExtras.dll', 
'./output/main.dist/PySide6/qml/QtCharts', 
'./output/main.dist/PySide6/qt-plugins/qmltooling/qmldbg_debugger.dll',
'./output/main.dist/PySide6/qml/QtTest', 
'./output/main.dist/PySide6/Qt6QuickTimeline.dll',
'./output/main.dist/PySide6/Qt6WebEngineCore.dll', 
'./output/main.dist/PySide6/Qt6Sql.dll', 
'./output/main.dist/PySide6/Qt6LabsWavefrontMesh.dll', 
'./output/main.dist/PySide6/translations/qtdeclarative_fi.qm',
'./output/main.dist/PySide6/Qt63DInput.dll', 
'./output/main.dist/PySide6/translations/qtbase_es.qm',
'./output/main.dist/PySide6/Qt6Pdf.dll', 
'./output/main.dist/PySide6/Qt6Concurrent.dll', 
'./output/main.dist/PySide6/qt-plugins/tls', 
'./output/main.dist/PySide6/Qt6Charts.dll', 
'./output/main.dist/PySide6/Qt6ChartsQml.dll', 
'./output/main.dist/libssl-1_1.dll', 
'./output/main.dist/PySide6/translations/qtdeclarative_nn.qm', 
'./output/main.dist/PySide6/Qt6Quick3DRuntimeRender.dll', 
'./output/main.dist/PySide6/translations/qtbase_hr.qm',
'./output/main.dist/PySide6/translations/qtdeclarative_es.qm',
'./output/main.dist/PySide6/translations/qtbase_ko.qm', 
'./output/main.dist/PySide6/qt-plugins/qmltooling/qmldbg_quickprofiler.dll', 
'./output/main.dist/PySide6/Qt6QuickLayouts.dll',
'./output/main.dist/PySide6/qt-plugins/qmltooling/qmldbg_inspector.dll', 
'./output/main.dist/PySide6/translations/qtbase_uk.qm',
'./output/main.dist/PySide6/Qt6Multimedia.dll',
'./output/main.dist/PySide6/translations/qtdeclarative_ca.qm',
'./output/main.dist/PySide6/translations/qtbase_sk.qm', 
'./output/main.dist/PySide6/Qt6QmlXmlListModel.dll', 
'./output/main.dist/PySide6/Qt6Positioning.dll',
'./output/main.dist/PySide6/Qt6LabsSharedImage.dll', 
'./output/main.dist/PySide6/Qt6QuickParticles.dll',
'./output/main.dist/PySide6/Qt6DataVisualizationQml.dll', 
'./output/main.dist/PySide6/Qt63DQuickScene2D.dll',
'./output/main.dist/PySide6/translations/qtbase_pl.qm', 
'./output/main.dist/PySide6/translations/qtdeclarative_ko.qm', 
'./output/main.dist/PySide6/translations/qtbase_gd.qm', 
'./output/main.dist/PySide6/Qt6Quick3DAssetImport.dll',
'./output/main.dist/PySide6/Qt63DCore.dll', 
'./output/main.dist/PySide6/Qt6DataVisualization.dll',
'./output/main.dist/PySide6/Qt6Quick3D.dll',
'./output/main.dist/PySide6/translations/qtbase_he.qm',
'./output/main.dist/PySide6/Qt6LabsFolderListModel.dll', 
'./output/main.dist/PySide6/translations/qtbase_tr.qm',
'./output/main.dist/PySide6/qml/QtWebChannel',
'./output/main.dist/PySide6/Qt63DQuick.dll', 
'./output/main.dist/PySide6/Qt6LabsAnimation.dll', 
'./output/main.dist/PySide6/Qt6RemoteObjectsQml.dll',
'./output/main.dist/PySide6/translations/qtbase_ru.qm',
'./output/main.dist/PySide6/translations/qtbase_fa.qm',
'./output/main.dist/PySide6/Qt6SensorsQuick.dll', 
'./output/main.dist/PySide6/translations/qtdeclarative_ar.qm', 
'./output/main.dist/PySide6/translations/qtbase_nl.qm',
'./output/main.dist/PySide6/qt-plugins/qmltooling/qmldbg_local.dll', 
'./output/main.dist/PySide6/Qt6LabsSettings.dll', 
'./output/main.dist/PySide6/qt-plugins/qmltooling/qmldbg_tcp.dll', 
'./output/main.dist/PySide6/Qt6Quick3DParticles.dll', 
'./output/main.dist/PySide6/qml/QtWebEngine',
'./output/main.dist/PySide6/qt-plugins/qmltooling/qmldbg_profiler.dll', 
'./output/main.dist/libcrypto-1_1.dll',
'./output/main.dist/PySide6/qt-plugins/qmltooling/qmldbg_nativedebugger.dll', './output/main.dist/PySide6/translations/qtbase_fi.qm',
'./output/main.dist/PySide6/translations/qtdeclarative_zh_TW.qm', 
'./output/main.dist/PySide6/qt-plugins/qmltooling/qmldbg_server.dll', 
'./output/main.dist/PySide6/Qt6WebEngineQuickDelegatesQml.dll', 
'./output/main.dist/PySide6/Qt6PositioningQuick.dll',
'./output/main.dist/PySide6/Qt6WebSockets.dll',
'./output/main.dist/PySide6/translations/qtdeclarative_nl.qm',
'./output/main.dist/PySide6/Qt6Quick3DUtils.dll', 
'./output/main.dist/PySide6/Qt63DQuickExtras.dll', 
'./output/main.dist/PySide6/translations/qtdeclarative_tr.qm', 
'./output/main.dist/PySide6/Qt6QmlLocalStorage.dll', 
'./output/main.dist/PySide6/Qt6Quick3DAssetUtils.dll', 
'./output/main.dist/PySide6/translations/qtdeclarative_fr.qm', 
'./output/main.dist/PySide6/Qt6Quick3DEffects.dll', 
'./output/main.dist/PySide6/qml/QtScxml', 
'./output/main.dist/PySide6/translations/qtbase_zh_CN.qm', 
'./output/main.dist/PySide6/translations/qtbase_zh_TW.qm', 
'./output/main.dist/PySide6/translations/qtbase_bg.qm',
'./output/main.dist/PySide6/translations/qtbase_ca.qm', 
'./output/main.dist/PySide6/qml/QtSensors', 
'./output/main.dist/PySide6/translations/qtdeclarative_zh_CN.qm', 
'./output/main.dist/PySide6/Qt6Quick3DHelpers.dll', 
'./output/main.dist/PySide6/qt-plugins/qmltooling/qmldbg_preview.dll', 
'./output/main.dist/PySide6/Qt63DRender.dll', 
'./output/main.dist/PySide6/Qt6Test.dll', 
'./output/main.dist/PySide6/Qt3D', 
'./output/main.dist/PySide6/QtCharts', 
'./output/main.dist/PySide6/QtDataVisualization', 
'./output/main.dist/PySide6/QtMultimedia', 
'./output/main.dist/PySide6/QtPositioning', 
'./output/main.dist/PySide6/QtQuick3D', 
'./output/main.dist/PySide6/QtRemoteObjects', 
'./output/main.dist/PySide6/QtScxml', 
'./output/main.dist/PySide6/QtTest', 
'./output/main.dist/PySide6/QtSensors', 
'./output/main.dist/PySide6/QtWebChannel', 
'./output/main.dist/PySide6/QtWebEngine', 
'./output/main.dist/PySide6/QtWebSockets', 
'./output/main.dist/PySide6/Qt63DQuickAnimation.dll']


for item in listToDelete:
    if os.path.isfile(item):  # Check if the item is a file
        os.remove(item)  # Delete the file
        print("Deleted file:", item)
    elif os.path.isdir(item):  # Check if the item is a directory
         # Delete the empty directory
        #print(item)
        shutil.rmtree(item, ignore_errors=True)
        print("Deleted directory:", item)
    else:
        print("Invalid item:", item)
